#!/usr/bin/env python3
"""Auto-generate CLAUDE.md from pipeline/config.py.

Run automatically via Claude Code PostToolUse hook whenever pipeline files change.
Never edit CLAUDE.md by hand — edit config.py and this file re-generates it.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from pipeline.config import (
    STAGES, STAGE_LABELS, STEP_IO,
    TRANSCRIBE_MODEL, REWRITE_MODEL, REVIEW_MODEL, TRANSLATE_MODEL,
    REWRITE_MAX_CHARS, HEYGEN_RATIO, HEYGEN_RESOLUTION, HEYGEN_ENGINE,
)
from run_pipeline import ALL_STEPS  # 実行される工程だけ。残りは保留中。


SUSPENDED = [s for s in STEP_IO if s not in ALL_STEPS]


def _provider(model: str) -> str:
    """Model name picks the provider — same rule as pipeline/llm.py."""
    return "OpenAI" if model.startswith("gpt-") else "Gemini"


def _module_path(step: str) -> str:
    """Locate the module that implements a step, rather than assuming a package.

    API を叩く工程は pipeline/、ローカル処理だけの工程は tools/ にある。
    実在するファイルを見て決めるので、移動しても表が古くならない。
    """
    for cand in (f"pipeline/{step}.py", f"tools/{step}.py"):
        if (ROOT / cand).exists():
            return cand
    return "-"


# 利用者が受け取る最終成果物を作る工程（rewrite は parts/ 止まりなので含めない）
_FINAL_OUTPUTS = {"polish": "出力1", "translate": "出力2"}

# ステージ名だけでは足りない入出力の実体
_DETAIL = {
    "rewrite":          (None, "draft/parts/"),
    "assemble":         ("draft/parts/", "draft/_full.txt"),
    "polish":           ("draft/_full.txt", "narration/_full.txt"),
    "factcheck":        ("narration/_full.txt", "narration/_factcheck.md"),
    "split":            ("narration/_full.txt", "narration/parts/"),
    "translate":        ("narration/_full.txt", None),
    "heygen":           ("narration/parts/", "video/parts/"),
    "concat_video":     ("video/parts/", None),
}


def _pipeline_diagram() -> str:
    """One row per step: source → [step] → destination.

    連鎖の図にすると concat_narration（narration → narration）のように
    入出力が同じステージの工程で同じ行が重複してしまう。1工程1行なら
    分岐（narration から translate と heygen の2方向）も正しく表せる。
    """
    rows = []
    for step, (src, dst) in STEP_IO.items():
        d_src, d_dst = _DETAIL.get(step, (None, None))
        rows.append((d_src or f"{src}/", step, d_dst or f"{dst}/", step))
    w_src = max(len(r[0]) for r in rows)
    w_step = max(len(r[1]) for r in rows)

    lines = []
    for src, step, dst, name in rows:
        if name in SUSPENDED:
            note = "   （保留中・実行されない）"
        elif name in _FINAL_OUTPUTS:
            note = f"   ← {_FINAL_OUTPUTS[name]}"
        else:
            note = ""
        lines.append(f"  {src:<{w_src}} → [{step:<{w_step}}] → {dst}{note}")
    return "\n".join(lines)


def _stage_table() -> str:
    rows = ["| Stage dir | Contents |", "|-----------|----------|"]
    for stage in STAGES:
        rows.append(f"| `{stage}/` | {STAGE_LABELS.get(stage, stage)} |")
    return "\n".join(rows)


def _step_io_table() -> str:
    rows = ["| Step | Reads from | Writes to | Module | Status |",
            "|------|-----------|----------|--------|--------|"]
    for step, (src, dst) in STEP_IO.items():
        status = "**suspended**" if step in SUSPENDED else "active"
        rows.append(f"| `{step}` | `{src}/` | `{dst}/` | `{_module_path(step)}` | {status} |")
    return "\n".join(rows)


def _how_to_add_step() -> str:
    stage_list = '", "'.join(STAGES)
    return f'''\
1. Add the new stage name to `STAGES` in `pipeline/config.py` at the correct position.
   (Current order: `["{stage_list}"]`)
2. Add the step to `STEP_IO` with its `(input_stage, output_stage)`.
3. Create the module with `def run(project: str) -> list[Path]:` —
   `pipeline/<step>.py` if it calls an API, `tools/<step>.py` if it is local-only.
4. Add the step name to `ALL_STEPS` in `run_pipeline.py`.
5. Save and the hook will regenerate this file automatically.\
'''


def generate() -> str:
    return f"""\
<!-- AUTO-GENERATED by tools/gen_spec.py — DO NOT EDIT MANUALLY -->
<!-- Source of truth: pipeline/config.py — edit that file, not this one -->

# english_voice/avator — Pipeline Specification

## Overview

Turns an English audio file into an English narration script (SSML), its
Japanese translation, and a HeyGen avatar video.

## Pipeline Flow

```
{_pipeline_diagram()}
```

`narration/` は2つに分かれる: `translate` は `_full.txt` を、`heygen` は
`parts/_part*.txt` を読む。同じステージから別のファイルを読む二系統。

## Data Layout

Each source file becomes one **project directory** under `data/`:

```
data/
  inbox/                    drop zone — put source audio here
  senario_jp/               docx/pdf for the NotebookLM prompt generator
  {{project_slug}}/
    raw/                    raw input (m4a / mp4 / mp3)
    audio/                  converted mp3
    transcript/             English transcript, verbatim
    draft/
      parts/                  _part*.txt — narration draft (rewrite output)
                              _part*_review.md — what the review flagged
    narration/
      {{stem}}_full.txt       ← output 1: English narration script (SSML)
      parts/                  _part*.txt — reviewed segments (heygen input)
    translation/
      {{stem}}_ja.txt         ← output 2: Japanese translation
    video/                  ← output 3: avatar video (mp4)
      parts/
```

Stage directories use **semantic names** (not numbers).
Inserting a new step never requires renaming existing directories.
`_part*` files always live in `parts/`, never directly in the stage dir —
enforced by `tools/check_design.py`.

## Stage Reference

{_stage_table()}

## Step I/O Reference

{_step_io_table()}

## How to Add a New Step

{_how_to_add_step()}

## How to Run

```bash
./run.sh                            # everything in data/inbox/
./run.sh path/to/audio.m4a          # one specified file
./run.sh --no-video                 # stop before video generation
./run.sh --again                    # redo the latest project (implies --force)
./run.sh --steps convert,transcribe # specific steps
./run.sh --project my_project       # one project
./run.sh --force                    # ignore existing output and rebuild
./tool_llm_check.sh                 # which model each step uses
```

Each step is **idempotent** — existing output files are skipped unless `--force`.

Script names are prefixed by role: `run` = whole pipeline, `step_` = one stage,
`tool_` = outside the pipeline, `gen_` = produces an artifact.

## Models & Providers

**The model name picks the provider**: `gpt-*` → OpenAI, anything else → Gemini.
Dispatch lives in `pipeline/llm.py`; the step modules never talk to a provider SDK directly.
Switching provider = editing one line in `pipeline/config.py`.

| Constant | Value | Provider |
|----------|-------|----------|
| `TRANSCRIBE_MODEL` | `{TRANSCRIBE_MODEL}` | {_provider(TRANSCRIBE_MODEL)} |
| `REWRITE_MODEL` | `{REWRITE_MODEL}` | {_provider(REWRITE_MODEL)} |
| `REVIEW_MODEL` | `{REVIEW_MODEL}` | {_provider(REVIEW_MODEL)} |
| `TRANSLATE_MODEL` | `{TRANSLATE_MODEL}` | {_provider(TRANSLATE_MODEL)} |

The source audio is English, so transcription is verbatim — no language
conversion step is involved.

Per-run override without editing config:

```bash
./run.sh --model-rewrite gemini-3.6-flash
./run.sh --model-transcribe gemini-3.6-flash
./tool_llm_check.sh --live        # which provider each step resolves to + connectivity
```

## Other Key Constants (`pipeline/config.py`)

| Constant | Value |
|----------|-------|
| `REWRITE_MAX_CHARS` | `{REWRITE_MAX_CHARS}` |
| `HEYGEN_RATIO` | `{HEYGEN_RATIO}` |
| `HEYGEN_RESOLUTION` | `{HEYGEN_RESOLUTION}` |
| `HEYGEN_ENGINE` | `{HEYGEN_ENGINE}` |

## Environment

- Python 3.12, venv at `.venv/`
- VS Code auto-activates venv via `.vscode/settings.json`
- API keys in `.env` (gitignored): `GEMINI_API_KEY`, `OPENAI_API_KEY`, `HEYGEN_API_KEY`, `HEYGEN_AVATAR_ID`, `HEYGEN_VOICE_ID`
- Only the keys for the providers you actually use are required (clients are lazily initialised)

## GitHub

`git@github.com:OnozukaRikkyo/english_voice_avator.git`

## Claude Code

- This file is auto-regenerated by `tools/gen_spec.py` via PostToolUse hook.
- **Never edit this file manually** — edit `pipeline/config.py` instead.
- Hook config: `.claude/settings.json`
"""


def main() -> None:
    spec = generate()
    out = ROOT / "CLAUDE.md"
    current = out.read_text(encoding="utf-8") if out.exists() else ""
    if spec == current:
        return  # no change, no write
    out.write_text(spec, encoding="utf-8")
    print(f"[gen_spec] CLAUDE.md updated")


if __name__ == "__main__":
    main()
