#!/usr/bin/env python3
"""Auto-generate human-facing documentation in docs/.

Each public function generates one markdown file.
To add a new document:
  1. Add a function  gen_<name>() -> str  that returns the markdown content.
  2. Add it to DOCS_REGISTRY at the bottom of this file.
  3. Save — the PostToolUse hook regenerates all docs automatically.

Never edit files in docs/ by hand; edit this file instead.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
DOCS = ROOT / "docs"

sys.path.insert(0, str(ROOT))
from pipeline.config import (
    NARRATION_OPENING, PRESETS,
    STEP_IO, NOTEBOOKLM_PROMPT_MODEL,
    TRANSCRIBE_MODEL, REWRITE_MODEL, REVIEW_MODEL, TRANSLATE_MODEL,
)
from run_pipeline import ALL_STEPS  # active steps only — suspended ones are commented out there


# Steps that exist in STEP_IO but are not in ALL_STEPS are on hold.
SUSPENDED_STEPS = [s for s in STEP_IO if s not in ALL_STEPS]


def _hold(step: str) -> str:
    """保留中の工程には印を付ける。解除したら自動で消える。"""
    return "（保留中）" if step in SUSPENDED_STEPS else ""


def _video_help() -> str:
    if SUSPENDED_STEPS:
        return "`heygen` / `concat_video` は保留中です（`video_guide.md`）"
    return "`./run.sh --steps heygen,concat_video` で動画だけ作り直せます"


def _provider(model: str) -> str:
    """モデル名がプロバイダを決める — pipeline/llm.py と同じ規約。"""
    return "OpenAI" if model.startswith("gpt-") else "Gemini"



# ── Document generators ────────────────────────────────────────────────────────

def gen_user_guide() -> str:
    """docs/user_guide.md — 全体の入口。何ができて、どれを読めばいいか。"""
    steps_list = " → ".join(ALL_STEPS)
    suspended = (
        f"\n`{'` / `'.join(SUSPENDED_STEPS)}` は保留中で実行されません"
        "（詳細は `video_guide.md`）。\n" if SUSPENDED_STEPS else "\n"
    )
    return (
        "# ユーザーガイド\n"
        "\n"
        "このプロジェクトでできることは2つです。目的から選んでください。\n"
        "\n"
        "| やりたいこと | コマンド | 詳細 |\n"
        "|---|---|---|\n"
        "| 音声ファイルから英語ナレーション台本と日本語訳を作る | `./run.sh` | `video_guide.md` |\n"
        "| 日本語資料から NotebookLM 用プロンプトを作る | `./gen_notebooklm_prompt.sh` | `notebooklm_guide.md` |\n"
        "\n"
        "使うAIモデルの変更方法は `model_guide.md` にまとめています。\n"
        "\n"
        "---\n"
        "\n"
        "## はじめに（初回のみ）\n"
        "\n"
        "### 1. APIキーを設定する\n"
        "\n"
        "`.env` に書きます（git 管理外）。**実際に使う側だけ**あれば動きます。\n"
        "\n"
        "```\n"
        "GEMINI_API_KEY=...\n"
        "OPENAI_API_KEY=...\n"
        "HEYGEN_API_KEY=...        # 動画生成に必要\n"
        "HEYGEN_AVATAR_ID=...      # 使うアバター\n"
        "HEYGEN_VOICE_ID=...       # 使う音声\n"
        "```\n"
        "\n"
        "### 2. 設定を確認する\n"
        "\n"
        "```bash\n"
        "./tool_llm_check.sh\n"
        "```\n"
        "\n"
        "工程ごとにどのモデル・どの提供元を使う設定か、必要なキーが揃っているかが出ます。\n"
        "`--live` を付けると実際に呼び出して疎通確認します。\n"
        "\n"
        "---\n"
        "\n"
        "## 使い方A: 音声 → 台本・動画\n"
        "\n"
        "```bash\n"
        "cp your_audio.m4a data/inbox/    # 1. 置く\n"
        "./run.sh                          # 2. 実行する\n"
        "```\n"
        "\n"
        "**`./run.sh` は引数なしで最初から最後まで通します。**\n"
        f"`{steps_list}` が順に動きます。\n"
        "プロジェクト名は音声ファイル名から自動で付きます。\n"
        "入力音声は英語である前提です。\n"
        f"{suspended}"
        "\n"
        "音声を1本だけ指定して処理することもできます。\n"
        "\n"
        "```bash\n"
        "./run.sh path/to/audio.m4a\n"
        "```\n"
        "\n"
        "処理後は inbox から自動で片付けられるので、次のファイルを指定してまた\n"
        "実行するだけです。同名プロジェクトが既にある場合は上書きせず止まります。\n"
        "\n"
        "できあがるもの:\n"
        "\n"
        "```\n"
        "data/{プロジェクト名}/\n"
        "  narration/*_full.txt     ← 英語ナレーション台本（SSML）\n"
        "  translation/*_ja.txt     ← その日本語訳\n"
        "  video/*.mp4              ← 結合済みのアバター動画\n"
        "  narration/*_defects.md   ← 台本のどこを直し、何が残ったかの記録\n"
        "  narration/*_factcheck.md ← 配信前に一次ソースと照合すべき項目の表\n"
        "```\n"
        "\n"
        "### 台本の点検（polish 工程）\n"
        "\n"
        "`rewrite` が書いた台本は、そのままでは報道として危うい箇所を含みます。\n"
        "文字起こしに無い数字が足される、\"reportedly\" が落ちて推測が断定になる、\n"
        "同じ言い回しが何度も出る — 読み返しの効かない音声では、いずれも\n"
        "そのまま受け取られます。\n"
        "\n"
        "`polish` は **連結した台本の全文** に対して3つのパスを回します。\n"
        "\n"
        "| | 役割 |\n"
        "|---|---|\n"
        "| A 検出 | 書き換えず、欠陥の一覧だけを出す |\n"
        "| B パッチ | 「元の文 → 直した文」の組だけを出す（全文の書き直しはしない） |\n"
        "| C 検証 | 組ごとに数値・固有名詞・ヘッジが保たれているか確かめる |\n"
        "\n"
        "**文字列の置換はコードが行い、元の文が原文に厳密一致しない組は棄却します。**\n"
        "修正対象でない文が巻き添えで壊れることが、構造的に起きません。\n"
        "\n"
        "反復フレーズ・壊れたタグ・数字・表記揺れは `pipeline/defects.py` が\n"
        "コードで数えます。モデルに数えさせません。モデルが担うのは\n"
        "「修辞の反復」「文意の破綻」「必須要素の有無」「帰属とヘッジ」だけです。\n"
        "\n"
        "何を直し、何が残ったかは `narration/{stem}_defects.md` にあります。\n"
        "**残存欠陥のうち、構造・文意の破綻・事実に関わるものは配信前に\n"
        "手で直してください。**\n"
        "\n"
        "### 配信前の照合リスト（factcheck 工程）\n"
        "\n"
        "review は台本を**文字起こしと**突き合わせますが、素材そのものが\n"
        "誤っていれば通してしまいます。factcheck は完成した台本から、\n"
        "**現実と**照合すべき項目（人物と役職の対応・数値・日付・固有名詞）を\n"
        "リスク順の表 `narration/*_factcheck.md` に書き出します。\n"
        "検証自体は行いません — 照合は必ず人が一次ソースで行ってください。\n"
        "\n"
        "**リスク High の行は、照合が済むまで配信しないことをお勧めします。**\n"
        "とくに「人名と役職の組み合わせ」は AI が最も間違えやすく、\n"
        "誤っていたときの damage が最も大きい項目です（実例: ある将官の\n"
        "役職が断定で書かれ、周辺は正しくヘッジされていたため逆に目立った）。\n"
        "\n"
        "各工程は出力があるとスキップします。途中で止まっても `./run.sh` を\n"
        "もう一度実行すれば続きから進みます。作り直すときは `--force` が要ります。\n"
        "\n"
        "---\n"
        "\n"
        "## 使い方B: 資料 → NotebookLM プロンプト\n"
        "\n"
        "```bash\n"
        "cp your_doc.docx data/senario_jp/   # 1. 置く（.docx / .pdf）\n"
        "./gen_notebooklm_prompt.sh          # 2. 実行する\n"
        "```\n"
        "\n"
        "`data/senario_jp/prompts/*_prompt.txt` ができるので、\n"
        "中身をそのまま NotebookLM に貼り付けてください。\n"
        "\n"
        "---\n"
        "\n"
        "## よくある操作\n"
        "\n"
        "```bash\n"
        "./run.sh --steps transcribe            # 特定の工程だけ動かす\n"
        "./run.sh --force                       # 既存の出力を無視して作り直す\n"
        "./run.sh --provider openai             # 全工程を OpenAI に切り替える\n"
        "./run.sh --project スラッグ名          # 特定プロジェクトだけ処理する\n"
        "./run.sh --again                       # 既存を上書きして作り直す（引数不要）\n"
        "./run.sh --no-video                    # 動画を作らず台本と日本語訳まで\n"
        "./run_no_video.sh                      # 同上（近道）\n"
        "python tools/clean_data.py             # 生成物を全部消してやり直す\n"
        "./tool_test.sh                         # 自動テストを流す（課金なし）\n"
        "```\n"
        "\n"
        "テストはファイル編集のたびに自動実行され（`.claude/settings.json` のフック）、\n"
        "push すると GitHub Actions でも走ります。どちらも API を呼ばないため課金されません。\n"
        "\n"
        "---\n"
        "\n"
        "## スクリプト一覧\n"
        "\n"
        "接頭辞で役割が分かるようにしています。\n"
        "\n"
        "| 接頭辞 | 意味 |\n"
        "|---|---|\n"
        "| `run` | パイプラインを実行する |\n"
        "| `step_` | 単一工程だけを実行する（全プロジェクト対象） |\n"
        "| `tool_` | パイプライン外の確認・調査 |\n"
        "| `gen_` | 生成物を作る（NotebookLM プロンプト） |\n"
        "\n"
        "```\n"
        "run.sh                        パイプラインの唯一の入口\n"
        "  ./run.sh                      inbox の全件を処理する\n"
        "  ./run.sh <file>               音声1本を指定して処理する\n"
        "  ./run.sh --again              既存プロジェクトを上書きして作り直す\n"
        "  ./run.sh --no-video           動画を作らず台本と日本語訳まで\n"
        "run_no_video.sh               ./run.sh --no-video の近道\n"
        "gen_notebooklm_prompt.sh      資料 → NotebookLM プロンプト\n"
        "\n"
        "step_convert.sh               音声形式の変換\n"
        "step_transcribe.sh            文字起こし\n"
        "step_rewrite.sh               ナレーション台本の生成\n"
        "step_assemble.sh              パートを1本の台本に連結\n"
        "step_polish.sh                台本を全文で点検して修正\n"
        "step_factcheck.sh             配信前に照合すべき項目の表を生成\n"
        "step_split.sh                 HeyGen の上限で分割\n"
        "step_translate.sh             日本語訳\n"
        f"step_heygen.sh                アバター動画の生成{_hold('heygen')}\n"
        f"step_concat_video.sh          動画パートの結合{_hold('concat_video')}\n"
        "\n"
        "tool_llm_check.sh             モデルとAPIキーの確認\n"
        "tool_heygen_consent.sh        HeyGen アバターの同意リンク取得\n"
        "tool_heygen_test.sh           設定中のアバターと音声を短い文で1本確認\n"
        "tool_test_caption.sh          HeyGen 字幕の挙動テスト（調査済み・記録用）\n"
        "tool_investigate_caption.sh   HeyGen 字幕の実証調査（調査済み・記録用）\n"
        "tool_test.sh                  自動テスト（APIを呼ばない）\n"
        "```\n"
        "\n"
        "各スクリプトの2行目に役割が書いてあります。\n"
        "\n"
        "---\n"
        "\n"
        "## 困ったとき\n"
        "\n"
        "| 症状 | 対処 |\n"
        "|---|---|\n"
        "| `GEMINI_API_KEY が未設定です` / `OPENAI_API_KEY が未設定です` | `.env` に該当キーを追加。`./tool_llm_check.sh` で確認 |\n"
        "| 途中まで生成済みで先に進まない | 各工程は出力があるとスキップします。作り直すなら `--force` |\n"
        "| 出力が古い内容のまま | 同上。`--force` を付けるか `tools/clean_data.py` で消す |\n"
        "| モデルを変えたい | `./run.sh --provider openai`、または `pipeline/config.py` を編集（`model_guide.md`） |\n"
        f"| 動画が作られない | {_video_help()} |\n"
        "| 生成物が消えた | `data/` は git 管理外です。元音声から作り直せます |\n"
        "\n"
        "---\n"
        "\n"
        "## 中身を知りたい人向け\n"
        "\n"
        "- `CLAUDE.md` — パイプラインの仕様（`pipeline/config.py` から自動生成）\n"
        "- `pipeline/config.py` — ステージ定義・モデル定数。**設定の単一の情報源**\n"
        "- `pipeline/llm.py` — Gemini / OpenAI の呼び分け\n"
        "- `docs/` は `tools/gen_docs.py` から自動生成されます。直接編集しないでください\n"
    )



def gen_video_guide() -> str:
    """docs/video_guide.md — 音声から台本・動画までの毎回の実行手順。"""
    steps_list = " → ".join(ALL_STEPS)
    suspended = ""
    if SUSPENDED_STEPS:
        # ALL_STEPS から外した工程があるときだけ出る。現在は該当なし。
        suspended = (
            "\n"
            "## 保留中のステップ\n"
            "\n"
            f"`{'` / `'.join(SUSPENDED_STEPS)}` は現在**実行されません**。\n"
            "再開するには `run_pipeline.py` の `ALL_STEPS` に該当の工程を戻してください。\n"
        )
    return (
        "# 音声から台本・動画を作る手順\n"
        "\n"
        "毎回この3手順を繰り返します。\n"
        "\n"
        "| | やること | コマンド |\n"
        "|---|---|---|\n"
        "| 1 | 日本語資料から NotebookLM 用プロンプトを作る | `./gen_notebooklm_prompt.sh` |\n"
        "| 2 | NotebookLM で英語音声を作り、`data/inbox/` に置く | （手作業） |\n"
        "| 3 | 台本・翻訳・動画をまとめて作る | `./run.sh` |\n"
        "\n"
        "手順1のプロンプトからは、文字起こしに渡す用語ヒントも同時に作られます。\n"
        "詳しくは `notebooklm_guide.md` を参照してください。\n"
        "\n"
        "---\n"
        "\n"
        "## 1. 音声ファイルを inbox に置く\n"
        "\n"
        "```\n"
        "data/inbox/\n"
        "  your_audio.m4a   ← ここに置く\n"
        "```\n"
        "\n"
        "対応フォーマット: `.m4a` / `.mp4` / `.mp3`\n"
        "\n"
        "入力音声は英語である前提です（逐語で書き起こします）。\n"
        "\n"
        "変換は音声認識向けの設定（64kbps モノラル）で行います。約52分まで\n"
        "分割せずに1回で送れます。超える場合は無音の位置で分割します。\n"
        "\n"
        "`data/senario_jp/prompts/` に NotebookLM プロンプトがあると、その用語集を\n"
        "固有名詞のヒントとして文字起こしに渡します（綴りが安定します）。\n"
        "自前の用語を足したい場合は `data/senario_jp/vocabulary.txt` に1行1語で置きます。\n"
        "\n"
        "---\n"
        "\n"
        "## 2. パイプラインを実行する\n"
        "\n"
        "```bash\n"
        "./run.sh\n"
        "```\n"
        "\n"
        "**引数は不要です。** `data/inbox/` を読み、ファイル名からプロジェクトを\n"
        "自動で作り、下の全工程を最初から最後まで通します。\n"
        "\n"
        f"`{steps_list}`\n"
        "\n"
        "所要時間の目安（49分の音声・8分割での実測）:\n"
        "\n"
        "| 工程 | 目安 |\n"
        "|---|---|\n"
        "| `convert` | 20秒 |\n"
        "| `transcribe` | 1分 |\n"
        "| `rewrite` | 15分前後（分割した塊ごとにAPIを呼ぶ・作り直し込み） |\n"
        "| `assemble` | 即時 |\n"
        "| `polish` | 15分前後（1周につき検出・パッチ・検証で3回API） |\n"
        "| `factcheck` | 数分（台本全体を1回で読む） |\n"
        "| `split` | 即時 |\n"
        "| `translate` | 1〜2分 |\n"
        "| `heygen` | **最も長い**。動画1本あたり数分 × パート数 |\n"
        "| `concat_video` | 数十秒 |\n"
        "\n"
        "動画を除くと約30分、いずれも音声の長さにおおむね比例します。\n"
        "\n"
        "できあがるもの:\n"
        "\n"
        "```\n"
        "data/{プロジェクト名}/\n"
        "  narration/*_full.txt     ← 英語ナレーション台本（SSML）\n"
        "  translation/*_ja.txt     ← その日本語訳\n"
        "  video/*.mp4              ← 結合済みのアバター動画\n"
        "  narration/*_defects.md   ← 台本のどこを直し、何が残ったかの記録\n"
        "  narration/*_factcheck.md ← 配信前に一次ソースと照合すべき項目の表\n"
        "```\n"
        "\n"
        "録音・公開の前に `*_defects.md` の残存欠陥と `*_factcheck.md` の\n"
        "high 行に目を通してください（説明は `user_guide.md`）。\n"
        f"{suspended}"
        "\n"
        "---\n"
        "\n"
        "## 途中から再開する / 作り直す\n"
        "\n"
        "各工程は**出力が既にあればスキップ**します。途中で止まっても、\n"
        "`./run.sh` をもう一度実行すれば済んだ工程を飛ばして続きから進みます。\n"
        "\n"
        "逆に、同じ音声で作り直したいときはスキップされてしまうので `--force` が要ります。\n"
        "\n"
        "```bash\n"
        "./run.sh --force                      # 全工程を作り直す\n"
        "./run.sh --again                      # 同上（引数不要・直近のプロジェクトが対象）\n"
        "./run.sh --steps rewrite,translate    # 特定の工程だけやり直す\n"
        "```\n"
        "\n"
        "**`--force` は動画も作り直します。** HeyGen の生成分は課金対象なので、\n"
        "台本だけ直したいときは `--steps` で工程を絞ってください。\n"
        "\n"
        "---\n"
        "\n"
        "## 台本の分割\n"
        "\n"
        "HeyGen の入力上限は5,000字です。台本パートはこれを超えることがあるため\n"
        "（実測 6,416〜9,483字）、送る前に `<break>` の位置で自動的に割ります。\n"
        "1.5秒（章の転換）を優先し、足りなければ1.0秒・0.5秒へ降ります。\n"
        "文の途中では切りません。\n"
        "\n"
        "分けたときの動画は `_part01_01.mp4` のように枝番が付きます。\n"
        "1本に収まったパートは枝番なしのままです。\n"
        "\n"
        "---\n"
        "\n"
        "## 冒頭の挨拶\n"
        "\n"
        "台本の先頭には、毎回まったく同じ挨拶が自動で入ります。\n"
        "\n"
        "```\n"
        f"{NARRATION_OPENING}\n"
        "```\n"
        "\n"
        "AIには書かせていません。文言が回ごとにぶれないよう、`part01` の\n"
        "`<speak>` の中へ機械的に差し込んでいます。AIには「挨拶と名乗りは書くな、\n"
        "本題から始めろ」と指示しているので、二重になりません。\n"
        "\n"
        "文言を変えるときは `.env` に1行書きます（コードの編集は不要）。\n"
        "\n"
        "```\n"
        "NARRATION_OPENING=Hello everyone, and welcome back. <break time=\"0.5s\"/> "
        "I'm Bogdan Parkhomenko. <break time=\"1.5s\"/>\n"
        "```\n"
        "\n"
        "空にすれば挨拶を入れません。既定の「new journey（新しい旅の始まり）」は\n"
        "開設回向けの文言なので、回を重ねたら `welcome back` などへ差し替えてください。\n"
        "\n"
        "---\n"
        "\n"
        "## アバターと音声を変える\n"
        "\n"
        "`.env` の `HEYGEN_AVATAR_ID` / `HEYGEN_VOICE_ID` を書き換えます。\n"
        "変更後は短い文で1本だけ生成して確認できます（消費は最小）。\n"
        "\n"
        "```bash\n"
        "./tool_heygen_test.sh                 # 既定の短文で確認\n"
        "./tool_heygen_test.sh \"好きな文章\"     # 文章を指定して確認\n"
        "```\n"
        "\n"
        "出力は `/tmp/heygen_test.mp4` です。見た目・声・背景の緑・画面字幕が\n"
        "出ていないことを確認してください。\n"
        "\n"
        "**既に生成済みの動画は変わりません。** 新しいアバターは次に生成する分から\n"
        "適用されます。作り直すなら `--force` が必要です。\n"
        "\n"
        "---\n"
        "\n"
        "## 生成物をすべて消してやり直す\n"
        "\n"
        "```bash\n"
        "python tools/clean_data.py\n"
        "```\n"
        "\n"
        "`data/` 配下は丸ごと git 管理外です。すべて元音声から再生成できます。\n"
    )


def gen_notebooklm_guide() -> str:
    """docs/notebooklm_guide.md — how to generate a NotebookLM prompt from a document."""
    return (
        "# NotebookLM プロンプトの生成手順\n"
        "\n"
        "NotebookLM で音声を作る際に貼り付ける**システムプロンプト**を、\n"
        "手元の日本語資料から自動生成します。\n"
        "\n"
        "生成するのはプロンプトだけです。音声そのものは NotebookLM 側で作ります。\n"
        "\n"
        "## 手順\n"
        "\n"
        "### 1. 日本語資料を置く\n"
        "\n"
        "```\n"
        "data/senario_jp/\n"
        "  your_document.docx   ← ここに置く\n"
        "```\n"
        "\n"
        "対応フォーマット: `.docx` / `.pdf`\n"
        "\n"
        "### 2. 生成する\n"
        "\n"
        "```bash\n"
        "./gen_notebooklm_prompt.sh\n"
        "```\n"
        "\n"
        "### 3. 出力を NotebookLM に貼り付ける\n"
        "\n"
        "```\n"
        "data/senario_jp/prompts/\n"
        "  your_document_prompt.txt       ← これをそのまま貼り付ける\n"
        "  your_document_vocabulary.txt   ← 文字起こし用の綴りヒント（自動生成）\n"
        "```\n"
        "\n"
        "## 文字起こしとの連携\n"
        "\n"
        "プロンプトを生成すると、その用語集から**文字起こし用の綴りヒント**も\n"
        "同時に作られます。以降 `./run.sh` で音声を処理すると自動で読み込まれ、\n"
        "固有名詞の綴りが安定します（実測で `Kostyantynivka` → `Kostiantynivka`）。\n"
        "\n"
        "`_vocabulary.txt` は1行1語のただのテキストです。**辞書が誤っていれば\n"
        "その誤りを押し付けることになる**ので、気になる語は直してください。\n"
        "行を消せばその語は渡されません。手で直した内容は再抽出で上書きされません。\n"
        "\n"
        "資料と関係なく足したい語は `data/senario_jp/vocabulary.txt` に書きます。\n"
        "\n"
        "既存のプロンプトから作り直すこともできます（APIを呼ばないので無料）。\n"
        "\n"
        "```bash\n"
        "./gen_notebooklm_prompt.sh --vocabulary-only\n"
        "```\n"
        "\n"
        "## 生成されるプロンプトの中身\n"
        "\n"
        f"`{NOTEBOOKLM_PROMPT_MODEL}`（{_provider(NOTEBOOKLM_PROMPT_MODEL)}）が資料を読んで\n"
        "ドメイン（戦争・政治・経済・技術など）を判定し、そのドメインに合わせて次の3つを書き起こします。\n"
        "Web検索ツールを有効にしているため、用語の英語表記は実際に検索して確認されます。\n"
        "モデルの切り替え方は `model_guide.md` を参照してください。\n"
        "\n"
        "1. **Role & Objective** — ドメインに合った専門家の役割設定\n"
        "2. **Document-Specific Vocabulary Guide** — 資料に出てくる難解語の用語集。\n"
        "   対象読者は「その分野の知識がない一般的なアメリカ人成人」で、\n"
        "   本当に分からない語（マイナーな地名・型式名・略語・専門用語）だけを選びます\n"
        "3. **Core Instructions** — 参照すべき権威ある英語サイトの実名\n"
        "   （紛争なら isw.org、経済なら imf.org など）、資料に明示されていない\n"
        "   独自の分析視点の見つけ方（具体例2つ）、トーンと構成\n"
        "\n"
        "## 注意\n"
        "\n"
        "- `data/` は丸ごと git 管理外です。生成したプロンプトはローカルにのみ残ります\n"
        "- 用語集は自動生成なので、そのまま使う前に内容を確認してください\n"
        "  （生成物自身にもその旨の注記が入ります）\n"
        "- 生成元: `tools/gen_notebooklm_prompt.py`（プロンプト定義は `_META_PROMPT`）\n"
    )


def gen_model_guide() -> str:
    """docs/model_guide.md — how to switch each step between Gemini and OpenAI."""
    rows = "\n".join(
        f"| `{const}` | `{model}` | {_provider(model)} |"
        for const, model in (
            ("TRANSCRIBE_MODEL", TRANSCRIBE_MODEL),
            ("REWRITE_MODEL", REWRITE_MODEL),
            ("REVIEW_MODEL", REVIEW_MODEL),
            ("TRANSLATE_MODEL", TRANSLATE_MODEL),
        )
    )
    return (
        "# モデル・プロバイダの切り替え\n"
        "\n"
        "## 規約\n"
        "\n"
        "**モデル名がプロバイダを決めます。**\n"
        "`gpt-` で始まれば OpenAI、それ以外は Gemini。\n"
        "呼び分けは `pipeline/llm.py` が行い、各工程のコードは\n"
        "プロバイダのSDKを直接触りません。utimes プロジェクトと同じ規約です。\n"
        "\n"
        "## 現在の設定\n"
        "\n"
        "| 定数 | モデル | プロバイダ |\n"
        "|------|--------|-----------|\n"
        f"{rows}\n"
        "\n"
        "## 変え方は4通り\n"
        "\n"
        "優先順位は **個別指定 > プリセット > .env > config.py の既定値** です。\n"
        "\n"
        "### 1. 全工程をまとめて（この実行だけ）\n"
        "\n"
        "```bash\n"
        f"{''.join(f'./run.sh --provider {n}{chr(10)}' for n in sorted(PRESETS))}"
        "```\n"
        "\n"
        "中身は `pipeline/config.py` の `PRESETS` です。\n"
        "\n"
        "### 2. 1工程だけ（この実行だけ）\n"
        "\n"
        "```bash\n"
        "./run.sh --model-rewrite gemini-3.6-flash\n"
        "./run.sh --model-transcribe gemini-3.6-flash\n"
        "./gen_notebooklm_prompt.sh --model-notebooklm gemini-3.6-flash\n"
        "```\n"
        "\n"
        "プリセットと併用でき、個別指定が勝ちます。\n"
        "\n"
        "```bash\n"
        "./run.sh --provider openai --model-rewrite gemini-3.6-flash\n"
        "  → rewrite だけ Gemini、他は OpenAI\n"
        "```\n"
        "\n"
        "### 3. 恒久的に変える（コード編集なし・おすすめ）\n"
        "\n"
        "`.env` に定数名と同じ名前で書くだけです。雛形がコメントで入っています。\n"
        "\n"
        "```\n"
        "REWRITE_MODEL=gemini-3.6-flash\n"
        "TRANSLATE_MODEL=gpt-5.6-luna\n"
        "```\n"
        "\n"
        "`./tool_llm_check.sh` で反映を確認できます。\n"
        "\n"
        "### 4. 既定値そのものを変える\n"
        "\n"
        "`pipeline/config.py` の該当行を書き換えます。\n"
        "\n"
        "```python\n"
        'TRANSCRIBE_MODEL = _model("TRANSCRIBE_MODEL", "gpt-transcribe")     # OpenAI\n'
        'TRANSCRIBE_MODEL = _model("TRANSCRIBE_MODEL", "gemini-3.6-flash")   # Gemini\n'
        "```\n"
        "\n"
        "## 確認する\n"
        "\n"
        "```bash\n"
        "./tool_llm_check.sh                    # 工程ごとのモデルとプロバイダ、キーの有無\n"
        "./tool_llm_check.sh --provider openai  # プリセット適用後の姿を予習（変更はしない）\n"
        "./tool_llm_check.sh --live             # 実際に呼び出して疎通確認\n"
        "./tool_llm_check.sh --models           # 利用可能なモデル一覧\n"
        "```\n"
        "\n"
        "## 文字起こしについて\n"
        "\n"
        "入力音声は英語である前提です。書き起こしは逐語で行い、言語変換は挟みません\n"
        "（1音声につきAPI呼び出しは1回）。\n"
        "\n"
        "OpenAI のアップロード上限は25MBです。超える音声は `pipeline/llm.py` が\n"
        "ffmpeg で時間分割して個別に送り、結果を連結します。\n"
        "\n"
        "## モデル選定の考え方\n"
        "\n"
        "**作業の難易度で選びます。** 安いモデルで足りる工程だけ安くします。\n"
        "\n"
        "| 工程 | 難易度 | 理由 |\n"
        "|---|---|---|\n"
        "| rewrite | 最難 | 用語の正確さ・行間の分析・冗長の削り込み・SSML・意味単位での分割を同時に要求 |\n"
        "| review | 最難 | 裏付けのない断定・煽り・片側だけの視点を見つける。安いモデルは問題を見つけられない |\n"
        "| transcribe | 高 | 固有名詞の聞き取り。誤ると後段すべてが誤った前提で動き、取り返しがつかない |\n"
        "| notebooklm | 中〜高 | 検索の使い分けと、一般読者が分からない語だけを選ぶ取捨選択 |\n"
        "| translate | 中 | 翻訳自体は機械的だが、NHK準拠の固有名詞表記と論調の維持が要る |\n"
        "\n"
        "translate を lite に落とすのは推奨しません。実測で `gemini-2.5-flash-lite` は\n"
        "改行構造が123行→8行に崩れ、固有名詞も落ちました。\n"
        "\n"
        "## APIキー\n"
        "\n"
        "`.env`（git 管理外）に置きます。クライアントは遅延初期化なので、\n"
        "**実際に使う側のキーだけ**あれば動きます。\n"
        "\n"
        "```\n"
        "GEMINI_API_KEY=...\n"
        "OPENAI_API_KEY=...\n"
        "```\n"
        "\n"
        "## Web検索を使う工程\n"
        "\n"
        f"`tools/gen_notebooklm_prompt.py` は用語の正式な英語表記を実際に調べさせるため、\n"
        f"Web検索ツールを有効にして呼びます（`NOTEBOOKLM_PROMPT_MODEL` = "
        f"`{NOTEBOOKLM_PROMPT_MODEL}` / {_provider(NOTEBOOKLM_PROMPT_MODEL)}）。\n"
        "これも同じ規約で切り替わります。\n"
        "\n"
        "- **OpenAI** — Responses API の `web_search` ツール\n"
        "- **Gemini** — Google 検索グラウンディング\n"
        "\n"
        "```bash\n"
        "./gen_notebooklm_prompt.sh                              # 既定モデル\n"
        "./gen_notebooklm_prompt.sh --model-notebooklm gemini-3.6-flash  # この実行だけ変更\n"
        "```\n"
    )


# ── Registry & runner ─────────────────────────────────────────────────────────

# Map output filename → generator function
# To add a new doc: add an entry here.
DOCS_REGISTRY: dict[str, callable] = {
    "user_guide.md": gen_user_guide,
    "video_guide.md": gen_video_guide,
    "notebooklm_guide.md": gen_notebooklm_guide,
    "model_guide.md": gen_model_guide,
}


def main() -> None:
    DOCS.mkdir(exist_ok=True)
    for filename, generator in DOCS_REGISTRY.items():
        out = DOCS / filename
        content = generator()
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if content != current:
            out.write_text(content, encoding="utf-8")
            print(f"[gen_docs] docs/{filename} updated")


if __name__ == "__main__":
    main()
