#!/usr/bin/env python3
"""Auto-generate CLAUDE.md from pipeline/config.py.

Run automatically via Claude Code PostToolUse hook whenever pipeline files change.
Never edit CLAUDE.md by hand — edit config.py and this file re-generates it.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from pipeline.config import (
    STAGES, STAGE_LABELS, STEP_IO,
    GEMINI_TRANSCRIBE_MODEL, GEMINI_REWRITE_MODEL, REWRITE_MAX_CHARS,
    HEYGEN_RATIO,
)


def _pipeline_diagram() -> str:
    lines = []
    for step, (src, dst) in STEP_IO.items():
        src_label = STAGE_LABELS.get(src, src)
        dst_label = STAGE_LABELS.get(dst, dst)
        lines.append(f"  {src_label}")
        lines.append(f"    ↓ [{step}]")
    last_dst = list(STEP_IO.values())[-1][1]
    lines.append(f"  {STAGE_LABELS.get(last_dst, last_dst)}")
    return "\n".join(lines)


def _stage_table() -> str:
    rows = ["| Stage dir | Contents |", "|-----------|----------|"]
    for stage in STAGES:
        rows.append(f"| `{stage}/` | {STAGE_LABELS.get(stage, stage)} |")
    return "\n".join(rows)


def _step_io_table() -> str:
    rows = ["| Step | Reads from | Writes to | Module |",
            "|------|-----------|----------|--------|"]
    for step, (src, dst) in STEP_IO.items():
        rows.append(f"| `{step}` | `{src}/` | `{dst}/` | `pipeline/{step}.py` |")
    return "\n".join(rows)


def _how_to_add_step() -> str:
    stage_list = '", "'.join(STAGES)
    return f'''\
1. Add the new stage name to `STAGES` in `pipeline/config.py` at the correct position.
   (Current order: `["{stage_list}"]`)
2. Add the step to `STEP_IO` with its `(input_stage, output_stage)`.
3. Create `pipeline/<step>.py` with `def run(project: str) -> list[Path]:`.
4. Add the step name to `ALL_STEPS` in `run_pipeline.py`.
5. Save and the hook will regenerate this file automatically.\
'''


def generate() -> str:
    return f"""\
<!-- AUTO-GENERATED by tools/gen_spec.py — DO NOT EDIT MANUALLY -->
<!-- Source of truth: pipeline/config.py — edit that file, not this one -->

# english_voice/avator — Pipeline Specification

## Overview

Transforms podcast/news audio into an AI avatar video using HeyGen.

## Pipeline Flow

```
{_pipeline_diagram()}
```

## Data Layout

Each source file becomes one **project directory** under `data/`:

```
data/
  {{project_slug}}/
    raw/         raw input (m4a / mp4 / mp3)
    audio/       converted mp3
    transcript/  English transcript
    narration/   rewritten YouTube narration
    video/       avatar video (mp4)
```

Stage directories use **semantic names** (not numbers).
Inserting a new step never requires renaming existing directories.

## Stage Reference

{_stage_table()}

## Step I/O Reference

{_step_io_table()}

## How to Add a New Step

{_how_to_add_step()}

## How to Run

```bash
# Full pipeline (all projects)
python run_pipeline.py

# Specific steps
python run_pipeline.py --steps convert,transcribe

# Single project
python run_pipeline.py --project my_project

# Check HeyGen API / configured IDs
python heygen_check.py
```

Each step is **idempotent** — existing output files are skipped.

## Key Constants (`pipeline/config.py`)

| Constant | Value |
|----------|-------|
| `GEMINI_TRANSCRIBE_MODEL` | `{GEMINI_TRANSCRIBE_MODEL}` |
| `GEMINI_REWRITE_MODEL` | `{GEMINI_REWRITE_MODEL}` |
| `REWRITE_MAX_CHARS` | `{REWRITE_MAX_CHARS}` |
| `HEYGEN_RATIO` | `{HEYGEN_RATIO}` |

## Environment

- Python 3.12, venv at `.venv/`
- VS Code auto-activates venv via `.vscode/settings.json`
- API keys in `.env` (gitignored): `GEMINI_API_KEY`, `HEYGEN_API_KEY`, `HEYGEN_AVATAR_ID`, `HEYGEN_VOICE_ID`

## GitHub

`git@github.com:OnozukaRikkyo/english_voice_avator.git`

## Claude Code

- This file is auto-regenerated by `tools/gen_spec.py` via PostToolUse hook.
- **Never edit this file manually** — edit `pipeline/config.py` instead.
- Hook config: `.claude/settings.json`
"""


def main() -> None:
    spec = generate()
    out = ROOT / "CLAUDE.md"
    current = out.read_text(encoding="utf-8") if out.exists() else ""
    if spec == current:
        return  # no change, no write
    out.write_text(spec, encoding="utf-8")
    print(f"[gen_spec] CLAUDE.md updated")


if __name__ == "__main__":
    main()
